version: '3.5'

services:
  todo-app:
    build:
      context: todo/
      dockerfile: Dockerfile
    image: todo-app:v1
    restart: always
    ports:
      - '8081:8081'
    environment:
      - DATABASE_CONFIG={"host":"todo-db", "port":5432, "database":"todoapp", "user":"ziad", "password":"1234"}

  todo-db:
    image: postgres:13
    ports:
      - '5432:5432'
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=todoapp
      - POSTGRES_USER=ziad
    volumes:
      - todo-postgres:/var/lib/postgresql/data

  todo-ui:
    build: todo-ui/
    image: todo-ui:v1
    ports:
      - '8080:8080'

volumes:
  todo-postgres: